### ISSUE TITLE
Ausschalter moglichkeit fur die "ignoranten" im MP betrieb :-)

### ISSUE THREAD

**Issue by DonPaul75** [modelleicher/FS22_realismAddon_gearbox#11]
Hi, erst mal danke fur den tollen mod, macht richtig spass damit zu fahren. Hatte aber eine bitte gerne auch so, das ich nur meine kopie fur pirvates nutzen umstellen kann. Wir spieln in eine gruppe wo viele nur mit tastatur spielen, und nich so auf realismus stehen. Dagegen sind jungs, die voll mit controllern ausgestatet sind und gerne Dein mod auf dem server weiter nutzen wollen. Die bitte gehet um die moglichkkeit, das der mod bei MP betrieb individuell ein/ausschaltbar ist, also die die es nutzen wollen komplet damit funken, und fur die tastatur spieler komplet ausschaltbar ist (die wollen halt nicht beim anhalten auskupeln... und keine lust es zu lernen) Were so was moglich, wie gesagt gerne auch die kod zeilen einfach hier posten das die, die das selbe problem haben, selber umabuen koenen und dein mod somit ofiziel ungeendert bleibt. Danke im voraus fur Deine antwort und hoffentlich auch fur eine loesug.

**Comment by jason0611** [comment]
Hi,
die notwendige Anpassung, damit das Skript nur bei aktiver manueller Kupplung aktiv ist, findest Du unter #10 🙂. 
Viele Grüße,
Martin

**Comment by DonPaul75** [comment]
ok, werde ich gleich ausprobieren, Danke erst mal

**Comment by DonPaul75** [comment]
> Hi, die notwendige Anpassung, damit das Skript nur bei aktiver manueller Kupplung aktiv ist, findest Du unter #10 🙂. Viele Grüße, Martin

Danke noch mall, funkt jezt genau so, wie es sein soll auch ohne ausschalter :-)

**Comment by VenoushCZ** [comment]
Does this modification make the co-existing of RAGearbox and VCA possible?

**Comment by DonPaul75** [comment]
> 

I don't know about RAGearbox, but I use it with VCA without problems
