### ISSUE TITLE
Halbautomatisches Getriebe (bsp. Iseki TJV 985 von Gaints) fährt nicht rückwärts

### ISSUE THREAD

**Issue by ls22modding** [modelleicher/FS22_realismAddon_gearbox#13]
Hallo,
sehr geiles Addon allerdings ist mir noch ein Problem aufgefallen.
Bei Fahrzeugen mit Halbautomatischem Getriebe (z.B. dem Iseki TJV 985 von Gaints) wechselt der Schlepper sobald man in den Rückwärtsgang schaltet wieder in den Vorwärtsgang.

VG

**Comment by modelleicher** [comment]
Hallo,
Ja das ist ein bekannter Bug mit den Automatik-Getrieben die mit dem Valtra Patch gekommen sind - bin noch nicht dazu gekommen zu schauen woran das liegt
