### ISSUE TITLE
calc clutch ratio call und Problem mit Kupplung

### ISSUE THREAD

**Issue by rsmnn** [modelleicher/FS22_realismAddon_gearbox#16]
Hey, 
habe mir eben die aktuelle Version geladen und ein Problem.

Meine Log wird mit "calc clutch ratio call" zugespamt.
Ausserdem ist es bei mir so, dass wenn ich mit dem 7810 auf der Standartmap fahre und die Kupplung trete, der Traktor ausrollt und stehen bleibt. Sobald der fallende Drehzahlmesser bei 1000 rpm ankommt fährt der Traktor allerdings wieder los und lässt sich nicht mehr Anhalten.

Vielen Dank

**Comment by modelleicher** [comment]
Hallo, dass der Schlepper weiter fährt liegt daran dass du im Modus Manuell aber mit Automatischer Kupplung die Kupplung gar nicht benutzen kannst, zum anhalten musst du in Neutral schalten. Die Kupplung ist seitens Giants nur aktiv wenn man im "Manuell mit Kupplung" Modus ist.
Ich werde/sollte das evtl. mal noch fixen genau wie paar andere Dinge für Leute die nicht mit manueller Kupplung spielen wollen, aber das ist nicht in zwei Zeilen getan.

LG

**Comment by rsmnn** [comment]
Hallo, 
Sorry aber da hat mir wohl das letzte FS update ne Falle gestellt. Dieses hat er auch installiert als ich realismAddon_gearbox geupdatet habe. Auf meinem Spielstand wo alles lief, hatte ich plötzlich den Fehler und bin nicht drauf gekommen das es daran liegen könnte. 

Ich habe dennoch meine Log voll mit dem Eintrag "calc clutch ratio call"

LG

[log.txt](https://github.com/modelleicher/FS22_realismAddon_gearbox/files/10368434/log.txt)
