### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by doc3d** [modelleicher/FS22_realismAddon_gearbox#5]
First of all, many many thanks for creating this. Hopefully all issues can be solved.

When using it, I am noticing some strange behavior. It works until I exit and re-enter the cab. After that, the clutch cant be detected so I cant start up the tractor, or change gears if already running. If left running and in a gear, the vehicle starts moving and bogs down if you hold brake, so something seems to randomly "break"  making the clutch not detected. If I go to settings and select Automatic gears, save, and go back to manual with clutch, it works again until next time I jump out (occasionally seems to happen when changing from in-car to external camera as well, but less frequently)

Note: I have VCA installed but not active on the savegame (hope that compatibility gets fixed as well)

**Comment by doc3d** [comment]
Edit: I did some more research, as this phenomenon was happening even wehn disabling your mod, which surprised me. It turns out the culprit was "realistic Cab View" which I installed recently (to compensate for the loss of VCA I installed QuickCamera and realistic Cab view to get the same sort of option as I had with VCA). That means there is nothing wrong in this regard with your mod, and I appologize for jumping to that conclusion. I'll close the issue and report again if I find other issues in the future. Please keep up the excellent work.

**Comment by modelleicher** [comment]
Realistic Cab View is known for making the clutch not work unfortunately ;)
