### ISSUE TITLE
Enhanced Vehicle und Gearbox mod

### ISSUE THREAD

**Issue by Borsti95** [modelleicher/FS22_realismAddon_gearbox#9]
Moin,
Erstmal danke für diesen fantastischen mod. 

Aber was ich bemerkt habe das wenn ich die Handbremse nutze vom Enhanced Vehicle das die Bremsleuchten mein Aktivieren mit leuchten wwenn man im Fahrzeug sitzt, das passierte bevor ich den Gearbox mod aktiviert habe im Spiel nicht. Es ist eigentlich keine Große sache aber mein innerer monk sieht das anders. Deswegen dachte ich ich erwähne das mal XD

Vielleicht könnte man eine Feststellbremsen funktion mit in deinen mod einbauen. 
Denn ich nutze Enhanced Vehicle nur wegen dieser Funktion.

MfG Borsti Gaming

**Comment by modelleicher** [comment]
Moin,
Ja das mit den Bremslichtern muss ich noch in Griff kriegen bzw. überhaupt erst mal schauen warum das ist.. Mir ist auch fast so als wäre das erst seit einem der Patches so, zumindest bin ich mir 99% sicher dass das Anfangs nicht war :D
